from typing import Any, Dict, List

validations: List[Dict[str, Any]] = [
    {"name": "wc-test",
     "estimate_time": 600,
     },
    {"name": "mint validate",
     "estimate_time": 30,
     },
    {"name": "code coverage",
     "estimate_time": 20,
     },
    {"name": "flake8",
     "estimate_time": 10,
     "language": "python",
     },
    {"name": "mypy",
     "estimate_time": 10,
     "language": "python",
     },
    {"name": "xss",
     "estimate_time": 5,
     "language": "javascript",
     },
    {"name": "checkstyle",
     "estimate_time": 10,
     "language": "java",
     },
]